### PR TITLE
add a hack to the replacements registry to account for Mineralogy

### PR DESCRIPTION
**Pull request by dshadowwolf**

### CODE REVIEW

**Comment by SkyBlade1978** [comment]
Code looks fine to me, I wonder is there anything I can/should do in mineralogy so you don't need a workaround in OreSpawn?

**Comment by SkyBlade1978** [comment]
I wonder, what is instead of saying 'is mineralogy' you said 'is not minecraft', or tool in a list from the config JSON so its not hard coded to mineralogy specifically, that way it would be more generic? Dunno if that would cause mroe problems than it solved though...

**Review by jriwanek — APPROVED** [review]

**Comment by dshadowwolf** [comment]
I check specifically for Mineralogy, but... I really should be checking for "chert", "schist" and such - this is a stop-gap hack while I work on fleshing out a format for the "replacements" file (and 'registry') that allows for something like SQL for specifying stuff

**Comment by SkyBlade1978** [comment]
OK cool, well I certainly think the list of stuff it looks for should be in the config file (pre-populated with common stuff like chert etc as you said)

**Pull request merged**
